# Generated by Django 5.2 on 2025-04-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='duration',
            new_name='duration_minutes',
        ),
    ]
